<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tb_jpertanyaan extends CI_Controller
{
    
        
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tb_jpertanyaan_model');
        $this->load->library('form_validation');
        $this->load->model('My_model');
        $this->load->library('session');

        if ($this->session->userdata('level')!="admin") {
            redirect('login');
        }
    }

    public function index()
    {
        $tb_jpertanyaan = $this->Tb_jpertanyaan_model->get_all();

        $data = array(
            'tb_jpertanyaan_data' => $tb_jpertanyaan
        );

        $this->template->load('template','jenis_pertanyaan/tb_jpertanyaan_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Tb_jpertanyaan_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_jpertanyaan' => $row->id_jpertanyaan,
		'jenis_pertanyaan' => $row->jenis_pertanyaan,
	    );
            $this->template->load('template','jenis_pertanyaan/tb_jpertanyaan_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tb_jpertanyaan'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('tb_jpertanyaan/create_action'),
	    'id_jpertanyaan' => set_value('id_jpertanyaan'),
	    'jenis_pertanyaan' => set_value('jenis_pertanyaan'),
	);
        $this->template->load('template','jenis_pertanyaan/tb_jpertanyaan_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'jenis_pertanyaan' => $this->input->post('jenis_pertanyaan',TRUE),
	    );

            $this->Tb_jpertanyaan_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('tb_jpertanyaan'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Tb_jpertanyaan_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('tb_jpertanyaan/update_action'),
		'id_jpertanyaan' => set_value('id_jpertanyaan', $row->id_jpertanyaan),
		'jenis_pertanyaan' => set_value('jenis_pertanyaan', $row->jenis_pertanyaan),
	    );
            $this->template->load('template','jenis_pertanyaan/tb_jpertanyaan_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tb_jpertanyaan'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_jpertanyaan', TRUE));
        } else {
            $data = array(
		'jenis_pertanyaan' => $this->input->post('jenis_pertanyaan',TRUE),
	    );

            $this->Tb_jpertanyaan_model->update($this->input->post('id_jpertanyaan', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('tb_jpertanyaan'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Tb_jpertanyaan_model->get_by_id($id);

        if ($row) {
            $this->Tb_jpertanyaan_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('tb_jpertanyaan'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tb_jpertanyaan'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('jenis_pertanyaan', 'jenis pertanyaan', 'trim|required');

	$this->form_validation->set_rules('id_jpertanyaan', 'id_jpertanyaan', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

    public function word()
    {
        header("Content-type: application/vnd.ms-word");
        header("Content-Disposition: attachment;Filename=tb_jpertanyaan.doc");

        $data = array(
            'tb_jpertanyaan_data' => $this->Tb_jpertanyaan_model->get_all(),
            'start' => 0
        );
        
        $this->load->view('tb_jpertanyaan_doc',$data);
    }

}

/* End of file Tb_jpertanyaan.php */
/* Location: ./application/controllers/Tb_jpertanyaan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-18 08:14:14 */
/* http://harviacode.com */