<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Admin_model extends CI_Model
{

    function barang_max(){
                    $this->db->join('tb_stok s','s.id_barang = tb_barang.id_barang');
                    $this->db->order_by('stok','desc');
                    $this->db->limit(5);
            $query= $this->db->get('tb_barang');
            return $query;
    }

    function barang_min(){
                $this->db->join('tb_stok s','s.id_barang = tb_barang.id_barang');
                $this->db->order_by('stok','asc');
                $this->db->limit(5);
            $query= $this->db->get('tb_barang');
            return $query;
    }

    function grap_brand(){
                $this->db->select('count(id_brand) as jml,stok,nama_brand');
                $this->db->from('tb_barang');
                $this->db->join('tb_brand b','b.id_brand = tb_barang.brand');
                $this->db->join('tb_stok s','s.id_barang = tb_barang.id_barang');
                $this->db->group_by('brand');   
        $data = $this->db->get()->result();
        return $data;
    }

    function grap_kategori(){
                $this->db->select('count(id_kategori) as jml,stok,nama_kategori');
                $this->db->from('tb_barang');
                $this->db->join('tb_kategori k','k.id_kategori = tb_barang.kategori');
                $this->db->join('tb_stok s','s.id_barang = tb_barang.id_barang');
                $this->db->group_by('kategori');   
        $data = $this->db->get()->result();
        return $data;
        }

    


}

/* End of file Admin_model.php */
/* Location: ./application/models/Admin_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-18 07:39:35 */
/* http://harviacode.com */