<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tb_barang_model extends CI_Model
{

    public $table = 'tb_barang';
    public $id = 'id_barang';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function kode(){
        $this->db->select('RIGHT(tb_barang.id_barang,2) as kode_barang', FALSE);
        $this->db->order_by('kode_barang','DESC');    
        $this->db->limit(1);    
        $query = $this->db->get('tb_barang');  //cek dulu apakah ada sudah ada kode di tabel.    
        if($query->num_rows() <> 0){      
             //cek kode jika telah tersedia    
             $data = $query->row();      
             $kode = intval($data->kode_barang) + 1; 
        }
        else{      
             $kode = 1;  //cek jika kode belum terdapat pada table
        }
            $tgl=date('dmY'); 
            $batas = str_pad($kode, 5, "0", STR_PAD_LEFT);    
            $kodetampil = "BR"."5".$tgl.$batas;  //format kode
            return $kodetampil;  
       }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_barang', $q);
	$this->db->or_like('part_number', $q);
	$this->db->or_like('deskripsi', $q);
	$this->db->or_like('kategori', $q);
	$this->db->or_like('brand', $q);
	$this->db->or_like('satuan', $q);
	$this->db->or_like('move_tipe', $q);
	$this->db->or_like('cur_harga', $q);
	$this->db->or_like('harga', $q);
	$this->db->or_like('gambar', $q);
	$this->db->or_like('ket', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_barang', $q);
	$this->db->or_like('part_number', $q);
	$this->db->or_like('deskripsi', $q);
	$this->db->or_like('kategori', $q);
	$this->db->or_like('brand', $q);
	$this->db->or_like('satuan', $q);
	$this->db->or_like('move_tipe', $q);
	$this->db->or_like('cur_harga', $q);
	$this->db->or_like('harga', $q);
	$this->db->or_like('gambar', $q);
	$this->db->or_like('ket', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tb_barang_model.php */
/* Location: ./application/models/Tb_barang_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-11-10 03:37:04 */
/* http://harviacode.com */