<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tb_issuing_model extends CI_Model
{

    public $table = 'tb_issuing';
    public $id = 'id_issuing';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_issuing', $q);
	$this->db->or_like('tgl', $q);
	$this->db->or_like('no_ref', $q);
	$this->db->or_like('picker', $q);
	$this->db->or_like('remarks', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_issuing', $q);
	$this->db->or_like('tgl', $q);
	$this->db->or_like('no_ref', $q);
	$this->db->or_like('picker', $q);
	$this->db->or_like('remarks', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function get_picker($uri){
        $this->db->select('*');
        $this->db->from('tb_barang b');
        $this->db->join('tb_issuing_item s1','b.id_barang = s1.id_barang');
        $this->db->join('tb_issuing s2','s1.id_issuing = s2.id_issuing');
        $this->db->join('tb_stok st','b.id_barang = st.id_barang');
        $this->db->join('tb_satuan s','b.satuan = s.id_satuan');
        $this->db->join('tb_kategori k','b.kategori = k.id_kategori');
        $this->db->join('tb_brand br','b.brand = br.id_brand');
        $this->db->where(['s2.id_issuing' => $uri]);
        $data = $this->db->get();
        return $data;
}

}

/* End of file Tb_issuing_model.php */
/* Location: ./application/models/Tb_issuing_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-11-10 05:19:36 */
/* http://harviacode.com */