<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tb_jawaban_model extends CI_Model
{

    public $table = 'tb_jawaban';
    public $id = 'id_jawaban';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_all_query(){
        $sql = "SELECT j.id_jawaban,j.id_mahasantri,j.id_pertanyaan,j.jawaban,m.nama 
                FROM tb_jawaban as j, tb_mahasantri as m 
                WHERE j.id_mahasantri=m.id_mahasantri";
        return $this->db->query($sql)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_jawaban', $q);
	$this->db->or_like('id_mahasantri', $q);
	$this->db->or_like('id_pertanyaan', $q);
	$this->db->or_like('jawaban', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_jawaban', $q);
	$this->db->or_like('id_mahasantri', $q);
	$this->db->or_like('id_pertanyaan', $q);
	$this->db->or_like('jawaban', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tb_jawaban_model.php */
/* Location: ./application/models/Tb_jawaban_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-18 08:13:59 */
/* http://harviacode.com */