<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tb_pertanyaan_model extends CI_Model
{

    public $table = 'tb_pertanyaan';
    public $id = 'id_pertanyaan';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_all_query(){
        $sql = "SELECT p.id_pertanyaan,p.id_jpertanyaan,p.id_kuisioner,p.pertanyaan,p.pilihan,j.jenis_pertanyaan 
                FROM tb_pertanyaan as p, tb_jpertanyaan as j 
                WHERE p.id_jpertanyaan=j.id_jpertanyaan";
        $sql = "SELECT p.id_pertanyaan,p.id_jpertanyaan,p.id_kuisioner,p.pertanyaan,p.pilihan,k.kuisioner 
                FROM tb_pertanyaan as p, tb_kuisioner as k 
                WHERE p.id_kuisioner=k.id_kuisioner";
        return $this->db->query($sql)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_pertanyaan', $q);
	$this->db->or_like('id_jpertanyaan', $q);
	$this->db->or_like('id_kuisioner', $q);
	$this->db->or_like('pertanyaan', $q);
	$this->db->or_like('pilihan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_pertanyaan', $q);
	$this->db->or_like('id_jpertanyaan', $q);
	$this->db->or_like('id_kuisioner', $q);
	$this->db->or_like('pertanyaan', $q);
	$this->db->or_like('pilihan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tb_pertanyaan_model.php */
/* Location: ./application/models/Tb_pertanyaan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-18 08:05:14 */
/* http://harviacode.com */